// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oziscamwpncynbxmalfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96aXNjYW13cG5jeW5ieG1hbGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTk3MzUsImV4cCI6MjA2NDM3NTczNX0.M5M-gR52bUTntj_QlgMgMM2HXg6X26rVgP8H4NdhWQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);